spring:
  application:
    name: lionminiboard

  datasource:
    url: jdbc:mysql://localhost:3306/example_data
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8080